dist: trusty
os: linux

language: node_js
node_js:
  - "10"

dist: xenial

addons:
  apt:
    packages:
      - dpkg
  chrome: stable

cache:
  directories:
    - ./node_modules
    
install:
  - npm install

script:
  - npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
  - npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js
