dist: trusty
os: linux

language: node_js
node_js:
  - "10"

addons:
  chrome: stable

cache:
  directories:
    - ./node_modules
before_script:
  - chromedriver-update 89.0.4389.90

install:
  - npm install

script:
  - npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
  - npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js
